### ISSUE TITLE
Build failed due to `null array`

### ISSUE THREAD

**Issue by andrikoz** [creek-service/creek-json-schema-gradle-plugin#258]
**Describe the bug**
After including `org.creekservice.schema.json` plugin my module build 

**To Reproduce**
Gradle version: tested both in 8.8 and 8.5
Plugin verison (org.creekservice.schema.json) : 0.4.1

**Expected behavior**
Build to pass

**Actual behaviour**
Build is failing 

**Screenshots**

**Version info**
 - Creek version 0.4.1
 - OSX

**Additional context**
Build logs:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not load the value of field `capturedArgs` of `java.lang.invoke.SerializedLambda` bean found in field `spec` of `org.gradle.api.internal.tasks.execution.SelfDescribingSpec` bean found in field `specs` of `org.gradle.api.specs.AndSpec` bean found in field `specHolder` of `org.gradle.api.internal.tasks.execution.DescribingAndSpec` bean found in field `onlyIfSpec` of task `:property-module:property-domain:generateJsonSchema` of type `org.creekservice.api.json.schema.gradle.plugin.task.GenerateJsonSchema`.
> java.lang.reflect.InvocationTargetException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

Stack trace:
`Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.configurationcache.serialization.codecs.jos.JavaObjectSerializationCodec.readResolve(JavaObjectSerializationCodec.kt:194)
        at org.gradle.configurationcache.serialization.codecs.jos.JavaObjectSerializationCodec.decode(JavaObjectSerializationCodec.kt:109)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
        at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:269)
        at org.gradle.configurationcache.serialization.codecs.NonPrimitiveArrayCodec.decode(ArrayCodecs.kt:43)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
        at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:269)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:106)
        ... 171 more
Caused by: java.io.InvalidObjectException: null array
        ... 182 more
`

**Comment by big-andy-coates** [comment]
Hi @andrikoz, thanks for reporting.

Weird that you're seeing issues with Gradle 8.5, as that's the version of Gradle the repo uses itself, and a version that is explicitly tested.

If you can knock up a quick repo with a reproducible minimal case, then I'm more than happy to take a look.

**Comment by andrikoz** [comment]
Thanks @big-andy-coates , most probably the problem existed in cache configuration 

I used 
`--no-configuration-cache`
And seems that the issues is solved

**Comment by big-andy-coates** [comment]
Good to hear.

If you can provide reproducible steps I can dive into it and work out the cause
